# Generated by Django 5.1.5 on 2025-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_phone', models.ImageField(upload_to='images/phone/')),
                ('image_web', models.ImageField(upload_to='images/web/')),
                ('redirect_url_phone', models.URLField()),
                ('redirect_url_web', models.URLField()),
                ('title_phone', models.CharField(max_length=255)),
                ('title_web', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('availability', models.CharField(choices=[('web_only', 'Web Only'), ('phone_only', 'Phone Only'), ('both', 'Both')], max_length=20)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
