# Generated by Django 5.1.5 on 2025-02-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
